name: recommendation
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - seaborn
  - scikit-learn
  - statsmodels
  - pandas
  - scipy
  - matplotlib
  - numpy
  - jupyterlab
  - jupyter
  - ipykernel
  - scikit-surprise